/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { MeshStandardMaterial, DoubleSide } from 'three';
import { useGLTF } from "@react-three/drei";
import usePlane from "../stores/usePlane";

export function Plane(props) {
    const { nodes } = useGLTF("./models/paper_plane_01.glb");
    const color = usePlane((state) => state.color)
    const variant = usePlane((state) => state.variant)

    const material = new MeshStandardMaterial({
        color: color,
        metalness: 0,
        roughness: 1,
        side: DoubleSide,
    })

    return (
        <group {...props} dispose={null}  >
            {variant === "1" && (
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes["Plane_Material_#2_0"].geometry}
                    material={material}
                />
            )}
            {variant === "2" && (
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes["Plane001_Material_#2_0"].geometry}
                    material={material}
                />
            )}
            {variant === "3" && (
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes["Plane003_Material_#2_0"].geometry}
                    material={material}
                />
            )}
            {variant === "4" && (
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes["Plane002_Material_#2_0"].geometry}
                    material={material}
                />
            )}
        </group>
    );
}

useGLTF.preload("./models/paper_plane_01.glb");