/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Sources: https://sketchfab.com/curiositysphere
*/

import React, { useRef } from "react";
import { MeshStandardMaterial } from 'three';
import { useGLTF } from "@react-three/drei";

const material = new MeshStandardMaterial({
    color: 'tomato',
    metalness: 0,
    roughness: 1,
})
const modelProps = {
    position: [0, 0, 0],
    rotation: [-Math.PI / 2, 0, 0],
    dispose: null,
}
export function Cloud01(props) {
    const { nodes } = useGLTF("./models/cloud_01.glb");

    return (
        <group scale={100} {...modelProps} {...props}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cloud__0.geometry}
                material={material}
            />
        </group>
    );
}
useGLTF.preload("./models/cloud_01.glb");

export function Cloud02(props) {
    const { nodes } = useGLTF("./models/cloud_02.glb");
    return (
        <group scale={1} {...modelProps} {...props}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cloud02.geometry}
                material={material}
            />
        </group>
    );
}
useGLTF.preload("./models/cloud_02.glb");
