/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Source: https://poly.pizza/m/i0PZVuVlYv
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import useConfigurator from "./stores/useConfigurator";

export function Crown(props) {
    const { nodes, materials } = useGLTF("./models/crown.glb");
    const colors = useConfigurator((state) => state.colors)

    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI * 0.3, -Math.PI * 0.1, 0]} scale={100}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Crown2_1.geometry}
                >
                    <meshStandardMaterial color={colors.crown} />
                </mesh>
                <mesh
                    castShadow
                    receiveShadow
                    scale={0.9}
                    geometry={nodes.Crown2_2.geometry}
                >
                    <meshStandardMaterial color={[1.1, 1.1, 1.1]} toneMapped={false} />
                </mesh>
            </group>
        </group>
    );
}

useGLTF.preload("./models/crown.glb");
