/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Source: https://poly.pizza/m/i0PZVuVlYv
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Crown(props) {
    const { nodes, materials } = useGLTF("./models/crown.glb");
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI * 0.25, 0, 0]} scale={100}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Crown2_1.geometry}
                    material={materials.Gold}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Crown2_2.geometry}
                    material={materials.Red}
                />
            </group>
        </group>
    );
}

useGLTF.preload("./models/crown.glb");
