/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Source: https://market.pmnd.rs/model/formation-large-rock
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Rock(props) {
    const { nodes, materials } = useGLTF("./models/rock.gltf");
    return (
        <group {...props} dispose={null}>
            <group position={[0, 0, 0]} scale={1}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.formation_rock_1.geometry}
                    material={materials["wood.008"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.formation_rock_2.geometry}
                    material={materials.sand}
                />
            </group>
        </group>
    );
}

useGLTF.preload("./models/rock.gltf");