/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Crystal byiPoly3D
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Crystal(props) {
    const { nodes, materials } = useGLTF("/models/crystal.glb");
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.crystal_27.geometry}
                material={nodes.crystal_27.material}
                scale={50}
            />
        </group>
    );
}

useGLTF.preload("/models/crystal.glb");